{{- if .Values.web.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "slack-invite-mgr.fullname" . }}-web
  labels:
    {{- include "slack-invite-mgr.web.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.web.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "slack-invite-mgr.web.selectorLabels" . | nindent 4 }}
{{- end }}
