apiVersion: v2
name: slack-invite-mgr
description: A Helm chart for deploying Slack Invite Manager to Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - slack
  - invite
  - management
maintainers:
  - name: Steve Bennett
